# PARAMETRES DB - PARAMETRES APP
spring.application.name=Tenda-JOAM
spring.datasource.url=jdbc:mysql://localhost:3306/tendajoam?useSSL=false&serverTimezone=UTC
spring.datasource.username=joam
spring.datasource.password=P@ssw0rd

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8081

# DADES MAIL 
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tendajoam@gmail.com
spring.mail.password=zjayxgsiirrolmlq
spring.mail.protocol=smtp

# PROPIETATS SMTP
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# TAMANY MAXIM DE PUJADA D'ARXIUS
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB